### ISSUE TITLE
Does not check modification times on included files

### ISSUE THREAD

**Issue by Matchlighter** [andreyfedoseev/django-less#20]
After `LESS_MTIME_DELAY`, `.less` files with `@include "<FILE>"` do not register as needing to be recompiled if the imported file, but not the main file, has been changed.

**Comment by jjimenezlopez** [comment]
I have been thinking in this issue, the solution in my commit 40c4628 works fine. But I'm doubting if it is the best solution.

I think that would be good, make that if LESS_USE_CACHE is True, the css will be generated every load.

**Comment by Matchlighter** [comment]
@jjimenezlopez I tend to agree that it may not be the best solution, especially if the files aren't in the same directory... I'm not super-familiar w/ the code base, but it looks like you could do a RegExp to find `@import`/`@include` lines. However, performance may become a concern.

**Comment by jjimenezlopez** [comment]
Yeah, that was my first thought. I did not implement it because of lack of time. But, as you said, the performance could suffer with that approach. I still think that a good solution could be to use the `LESS_USE_CACHE` as I said in the previous comment, that way, you could do `LESS_USE_CACHE = DEBUG` in settings.py, and the CSS just would be regenerated in development environment.

What do you think?

**Comment by Matchlighter** [comment]
That will work.
